# Base on stylelint-config-recommended
plugins:
  - stylelint-scss
rules:
  # ----------------------------------------------------------------------------
  # ERRORS
  # See https://stylelint.io/user-guide/rules/list#possible-errors
  # ----------------------------------------------------------------------------
  color-no-invalid-hex: true
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  string-no-newline: true
  unit-no-unknown: true
  property-no-unknown: true
  keyframe-declaration-no-important: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  # block-no-empty: false
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true
  media-feature-name-no-unknown: true
  comment-no-empty: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true

  # ----------------------------------------------------------------------------
  # LANGUAGE LIMITATIONS
  # See https://stylelint.io/user-guide/rules/list#limit-language-features
  # ----------------------------------------------------------------------------
  alpha-value-notation: "number"
  hue-degree-notation: "angle"
  length-zero-no-unit: true
  function-url-no-scheme-relative: true
  number-max-precision: 3
  shorthand-property-no-redundant-values: true
  # declaration-block-no-redundant-longhand-properties: true
  declaration-block-single-line-max-declarations: 1
  # selector-no-qualifying-type: true
  selector-pseudo-element-colon-notation: "double"
  no-unknown-animations: true

  # ----------------------------------------------------------------------------
  # STYLE
  # See https://stylelint.io/user-guide/rules/list#stylistic-issues
  # ----------------------------------------------------------------------------
  # color-hex-case: "upper"
  font-family-name-quotes: "always-where-recommended"
  function-name-case: "lower"
  function-max-empty-lines: 0
  function-parentheses-newline-inside: "always-multi-line"
  function-url-quotes: "always"
  function-whitespace-after: "always"
  # number-leading-zero: "always"
  number-no-trailing-zeros: true
  # string-quotes: "single"
  unit-case: "lower"
  value-keyword-case:
    - "lower"
    - ignoreKeywords:
      - /A\d/
  value-list-max-empty-lines: 0
  property-case: lower
  declaration-bang-space-after: "never"
  declaration-block-semicolon-newline-after: "always"
  declaration-block-semicolon-space-after: "always-single-line"
  declaration-block-trailing-semicolon: "always"
  block-closing-brace-empty-line-before: "never"
  # block-closing-brace-newline-after: "always"
  selector-attribute-brackets-space-inside: "never"
  selector-attribute-operator-space-after: "never"
  selector-attribute-operator-space-before: "never"
  selector-attribute-quotes: "always"
  selector-combinator-space-after: "always"
  selector-combinator-space-before: "always"
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: "lower"
  selector-pseudo-class-parentheses-space-inside: "never"
  selector-pseudo-element-case: "lower"
  selector-type-case: "lower"
  media-feature-colon-space-after: "always"
  media-feature-name-case: "lower"
  media-feature-parentheses-space-inside: "never"
  media-feature-range-operator-space-after: "always"
  media-feature-range-operator-space-before: "always"
  at-rule-name-case: "lower"
  at-rule-name-space-after: "always"
  comment-whitespace-inside: "always"
  max-empty-lines: 2
  no-eol-whitespace: true
  indentation: 2

  # ----------------------------------------------------------------------------
  # SCSS
  # See https://github.com/kristerkari/stylelint-scss#readme
  # ----------------------------------------------------------------------------
  scss/at-each-key-value-single-line: true
  scss/at-rule-no-unknown: true
  scss/at-else-if-parentheses-space-before: "always"
  # scss/at-extend-no-missing-placeholder: true
  scss/at-function-parentheses-space-before: "never"
  scss/at-if-closing-brace-newline-after: "always-last-in-chain"
  scss/at-if-no-null: true
  scss/at-import-no-partial-leading-underscore: true
  # scss/at-import-partial-extension: "never"
  scss/at-mixin-parentheses-space-before: "never"
  scss/dollar-variable-colon-space-after: "always"
  scss/dollar-variable-colon-space-before: "never"
  scss/dollar-variable-no-missing-interpolation: true
  # scss/double-slash-comment-whitespace-inside: "always"
  # scss/comment-no-empty: true
  # scss/dimension-no-non-numeric-values: true
  scss/operator-no-newline-after: true
  scss/operator-no-newline-before: true
  # scss/operator-no-unspaced: true
  scss/no-duplicate-mixins: true
